### PR TITLE
G4 changes

### PR DESCRIPTION
**Pull request by jmimu**
Hi,
Thank you for Dexctrack!
I made some modifications to be able to use a G4.
In this pull request there are only some small changes.
I'll add issues for the other errors I had.
Best regards,

### CODE REVIEW

**Comment by DexcTrack** [comment]
In your first pull request, 'Support G4 firmware versions from 2', the code changes look fine to me. However, I'd like the comment in line 105 to be updated to remove "Not sure about ".

**Comment by DexcTrack** [comment]
Your second pull request adds instructions to the README.md file. It's not clear to me why the suggested steps are required. I'm running almost the same system as you: Linux Mint 19.1, Python 2.7.17, python-sqlite 1.0.1-12, and everything works fine without having copied anything into the /etc/udev/rules.d/ directory. Maybe my user account has more privileges than yours does?

**Comment by DexcTrack** [comment]
The third pull request, Misc python, imports print_function into database_records.py. This is a file with no print calls in it. So why was this added?

The change to dexctrack.py, is quite extreme. Why are you specifying python3 in code which I've told people to run under python2? What does the `-*- coding: utf-8 -*-` line do here? Does it make the whole program run properly under Python3? I've designed my python code to support Python3, but the low level code in readdata.py and database_records.py which came from the dexcom_reader project had trouble running under Python3 when I tested it. Does your `-*- coding: utf-8 -*-` make it work properly under Python3?

**Comment by jmimu** [comment]
Hi, I agree for line 105.
For README.md, it was to make it work even if you are not in the dialout group (and to use the 80-dexcom.rules file of the project).
The print declaration in database_records.py is just to be able to make debug prints later.
I made a mistake with python3 shebang, sorry!
The coding line is used to make sure python takes all the characters of the file as utf-8, making possible to use non-ascii characters.

**Comment by DexcTrack** [comment]
> Hi, I agree for line 105.
> For README.md, it was to make it work even if you are not in the dialout group (and to use the 80-dexcom.rules file of the project).

So, it's an option to either add the user into the _**dialout**_ group (which I prefer) or take the steps you added. It should be written up as an optional step. Something like this ...

5. Set up permissions to provide the user serial port access to a connected USB device. Option **a)** or option **b)** below will do this.

    a) Add the user account to the _**dialout**_ group.

            On Debian-based or Ubuntu-based Linux systems:
            sudo addgroup <username> dialout
           
            On Fedora-based Linux systems:
            sudo usermod -a -G <username> dialout
    
       You may need to log out and back in to make sure the group membership is updated.

    b) Install **_udev_** rules to get access to device.

            sudo cp dexctrack/etc/udev/rules.d/80-dexcom.rules /etc/udev/rules.d/
            sudo udevadm control --reload-rules

> The print declaration in database_records.py is just to be able to make debug prints later.

I prefer not to merge in code changes for some vague possible future use.

> I made a mistake with python3 shebang, sorry!

> The coding line is used to make sure python takes all the characters of the file as utf-8, making possible to use non-ascii characters.

The file doesn't have any non-ascii characters, so why add this? Again, I prefer not to merge in code changes which serve no current purpose.

**Comment by DexcTrack** [comment]
I've merged in your changes to readdata.py and my suggested update to your changes for README.md.

**Comment by jmimu** [comment]
I tested it and it works fine!

**Pull request closed without merging**
